---
name: Params-Validate-Checks
version: 0.01
author:
  - 'Smylers <smylers@cpan.org>'
abstract: Named checks for use with Params::Validate
license: perl
requires:
  Params::Validate: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
provides:
  Params::Validate::Checks:
    file: lib/Params/Validate/Checks.pm
    version: 0.01
generated_by: Module::Build version 0.26
